create table service_men (
	id INT,
	age INT,
	name VARCHAR(50),
	service_id INT,
	contact_no VARCHAR(50),
	work_experience INT,
	availability VARCHAR(13)
);
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (1, 37, 'Stephanie Ninnotti', 1, '6056650039', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (2, 31, 'Kerr Over', 1, '4745160466', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (3, 35, 'Malorie Le Prevost', 1, '9004641114', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (4, 37, 'Gaelan Cainey', 1, '4719157303', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (5, 42, 'Jim Zanetti', 1, '1519125327', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (6, 46, 'Kip Baines', 1, '7527224274', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (7, 48, 'Jackqueline Graddon', 1, '4126777306', 6, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (8, 41, 'Frans Batrop', 1, '1765344298', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (9, 28, 'Roddie Dirkin', 1, '7025407770', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (10, 34, 'Kessia Bunclark', 1, '2835589426', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (11, 30, 'Ollie Seabrocke', 1, '5749041553', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (12, 34, 'Averyl Weeds', 1, '4148651006', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (13, 29, 'Carlie Vanetti', 1, '3324203076', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (14, 26, 'Helge Harbach', 1, '2404001591', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (15, 37, 'Rodger Ulyat', 1, '2408724644', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (16, 38, 'Nicko Laskey', 1, '7316024142', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (17, 31, 'Sandi Cavee', 1, '4364977368', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (18, 44, 'Verile Tregunna', 1, '2143828037', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (19, 39, 'Ruthi Yewen', 1, '1278698480', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (20, 27, 'Erinna Adamolli', 1, '5989621068', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (21, 48, 'Sibella Dagg', 1, '2578456628', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (22, 35, 'Malanie Crookston', 1, '3946014686', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (23, 31, 'Margeaux Locke', 1, '6719377098', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (24, 25, 'Leese Diggins', 1, '4234660427', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (25, 41, 'Egon Overal', 1, '8277611085', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (26, 49, 'Warren Arboin', 1, '9074987951', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (27, 34, 'Honor Sone', 1, '7124893530', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (28, 32, 'Cristal Frearson', 1, '9384341271', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (29, 30, 'Emeline Bulch', 1, '3878537336', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (30, 46, 'Venita Bartusek', 1, '4821210454', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (31, 42, 'Ladonna Nyssens', 1, '1792056494', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (32, 40, 'Angela Kemmey', 1, '5865427385', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (33, 31, 'Theadora MacRinn', 1, '4978298125', 9, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (34, 29, 'Vincenz Strother', 1, '4622448638', 2, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (35, 43, 'Freddie Folbige', 1, '4754121906', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (36, 33, 'Lewie Dunbobin', 1, '8157986959', 2, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (37, 33, 'Fayre Belward', 1, '3287356971', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (38, 41, 'Elizabeth Hanburry', 1, '9483725898', 7, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (39, 42, 'Catrina Jays', 1, '2329073914', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (40, 34, 'Benedict Blazewicz', 1, '3555077398', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (41, 48, 'Janek Blowing', 1, '4695042369', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (42, 32, 'Sibylle Gouldthorp', 1, '7613880078', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (43, 27, 'Cari Surridge', 1, '4982679288', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (44, 33, 'Hernando Shillitoe', 1, '8513209347', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (45, 28, 'Rhody Oldcote', 1, '7096557936', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (46, 32, 'Tybalt Kirimaa', 1, '1944592115', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (47, 34, 'Camel Swan', 1, '1461075897', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (48, 30, 'Eada Cund', 1, '6562764907', 9, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (49, 37, 'Francisco Vida', 1, '3572666636', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (50, 36, 'Joyan Scarsbrooke', 1, '1891544355', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (51, 37, 'Melvin Readman', 1, '1199752671', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (52, 43, 'Rickie Sate', 1, '6548542066', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (53, 35, 'Phebe Cressingham', 1, '1693287089', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (54, 42, 'Glendon Troake', 1, '6953889364', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (55, 45, 'Lurlene Speight', 1, '7443692368', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (56, 36, 'Cordy Matura', 1, '1663568814', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (57, 44, 'Rita Coalbran', 1, '1535310615', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (58, 48, 'Mervin Virgin', 1, '2958363345', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (59, 40, 'Jodi Kittley', 1, '5374286533', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (60, 43, 'Bria Rastall', 1, '1451463227', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (61, 43, 'Roselin Joblin', 1, '6195531369', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (62, 34, 'Jeff Folger', 1, '8753390310', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (63, 35, 'Haywood Eseler', 1, '9708833051', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (64, 41, 'Ferdie Bassom', 1, '8538961079', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (65, 36, 'Darrin Peddie', 1, '3613414963', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (66, 39, 'Nicoline Johnys', 1, '6996835225', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (67, 40, 'Codi Leveritt', 1, '2065720519', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (68, 35, 'Jarrad Ladbrook', 1, '3584698056', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (69, 50, 'Izak Owthwaite', 1, '8897091244', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (70, 44, 'Vincent McClenaghan', 1, '3733034784', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (71, 41, 'Bertie Stollberg', 1, '3511227623', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (72, 42, 'Rana Temple', 1, '4362191596', 7, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (73, 46, 'Cinda Ferraresi', 1, '9715686494', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (74, 25, 'Shirley Filgate', 1, '3982411848', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (75, 47, 'Isabelle Binnes', 1, '4744280478', 6, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (76, 25, 'Trevor Orteau', 1, '8802602583', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (77, 25, 'Wilie Brownhill', 1, '6045178087', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (78, 38, 'Jarid Martinot', 1, '7489988430', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (79, 42, 'Dionysus Piel', 1, '8557546209', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (80, 35, 'Gordan Meggison', 1, '9956475557', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (81, 37, 'Amalle Brekonridge', 1, '6367401312', 2, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (82, 48, 'Maurie Moore', 1, '1953959453', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (83, 33, 'Manon Naldrett', 1, '3252227898', 2, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (84, 41, 'Demetris Sylett', 1, '3883776092', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (85, 45, 'Lionello Bernet', 1, '9221515929', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (86, 47, 'Harper Swatridge', 1, '1889457128', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (87, 34, 'Marti McCerery', 1, '7011609986', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (88, 25, 'Clevie Andreia', 1, '4354574668', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (89, 37, 'Hiram Turmel', 1, '3688616448', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (90, 50, 'Gregorio Eacle', 1, '3188932044', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (91, 43, 'Marylinda Fullerton', 1, '7579746858', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (92, 38, 'Marget Khomishin', 1, '4765794605', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (93, 43, 'Fionna Gonnin', 1, '6417510619', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (94, 38, 'Morissa Bricket', 1, '6071339287', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (95, 45, 'Jefferson Windley', 1, '5039880739', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (96, 39, 'Prince Rushby', 1, '1016603813', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (97, 47, 'Athena Ben', 1, '9254668664', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (98, 31, 'Pia Gozzett', 1, '4259791152', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (99, 48, 'Alidia Confort', 1, '6947052183', 7, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (100, 35, 'Arlena Ramos', 1, '7416332427', 8, 'Available');
