insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (1, 'Baumbach-Paucek', 'general_hardware', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (2, 'O''Conner-Kerluke', 'general_hardware', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (3, 'Schultz-Olson', 'general_hardware', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (4, 'Carter-Keebler', 'electrical', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (5, 'Ruecker Inc', 'electrical', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (6, 'Funk-Jaskolski', 'electrical', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (7, 'Gutmann, Lowe and Raynor', 'electrical', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (8, 'Koelpin-McGlynn', 'furniture', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (9, 'Lowe, Wunsch and Metz', 'furniture', 'dummy-loc', 'dummy-link');
insert into MOCK_DATA (id, store_name, store_type, store_location, store_db_link) values (10, 'Pacocha-Goodwin', 'furniture', 'dummy-loc', 'dummy-link');
