create table service_men (
	id INT,
	age INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	service_id INT,
	phone_no VARCHAR(50),
	email VARCHAR(50),
	work_experience INT,
	availability VARCHAR(13)
);
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (1, 29, 'Horatius', 'Northwood', 1, '4622482768', 'hnorthwood0@va.gov', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (2, 25, 'Faith', 'Davenhall', 1, '6185779203', 'fdavenhall1@xing.com', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (3, 42, 'Dana', 'Dyball', 1, '4902077813', 'ddyball2@typepad.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (4, 30, 'Appolonia', 'Adnet', 1, '9052958998', 'aadnet3@wisc.edu', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (5, 44, 'Rochester', 'Goutcher', 1, '1813632668', 'rgoutcher4@cpanel.net', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (6, 47, 'Antonella', 'Bouchard', 1, '7206177493', 'abouchard5@state.gov', 10, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (7, 44, 'Pebrook', 'Oakenfield', 1, '9751515222', 'poakenfield6@gravatar.com', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (8, 28, 'Augustus', 'Mc Carroll', 1, '3489526590', 'amccarroll7@ovh.net', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (9, 33, 'Corri', 'Feldon', 1, '9958869768', 'cfeldon8@marketwatch.com', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (10, 38, 'Leoine', 'Weddell', 1, '9517682490', 'lweddell9@phoca.cz', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (11, 31, 'Gabriel', 'Wixey', 1, '7307393938', 'gwixeya@dailymail.co.uk', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (12, 28, 'Wendell', 'MacQuaker', 1, '9132895116', 'wmacquakerb@samsung.com', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (13, 33, 'Chrissie', 'Haseley', 1, '8158183876', 'chaseleyc@weebly.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (14, 40, 'Mohandis', 'Bogey', 1, '3697658969', 'mbogeyd@oakley.com', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (15, 26, 'Towny', 'Aldins', 1, '1208042042', 'taldinse@theguardian.com', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (16, 47, 'Art', 'Denmead', 1, '8487644098', 'adenmeadf@blinklist.com', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (17, 25, 'Philippe', 'Dietzler', 1, '9473218433', 'pdietzlerg@tripod.com', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (18, 42, 'Juliette', 'McGlynn', 1, '6171277736', 'jmcglynnh@blinklist.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (19, 37, 'Darnall', 'Crockett', 1, '4329487736', 'dcrocketti@wisc.edu', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (20, 33, 'Godfry', 'McIlvaney', 1, '7258936149', 'gmcilvaneyj@rambler.ru', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (21, 25, 'Rosco', 'Burnand', 1, '6795495594', 'rburnandk@meetup.com', 10, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (22, 50, 'Herman', 'Arnet', 1, '9627351611', 'harnetl@mozilla.org', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (23, 50, 'Jock', 'Picot', 1, '8739628122', 'jpicotm@newsvine.com', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (24, 45, 'Perry', 'Howman', 1, '7011885858', 'phowmann@europa.eu', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (25, 49, 'Allie', 'Paver', 1, '9809297872', 'apavero@nsw.gov.au', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (26, 29, 'Penn', 'Larimer', 1, '6261120292', 'plarimerp@newsvine.com', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (27, 36, 'Brandy', 'Brevetor', 1, '6406301608', 'bbrevetorq@wikispaces.com', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (28, 50, 'Darsie', 'Bitten', 1, '6247967954', 'dbittenr@huffingtonpost.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (29, 41, 'Kellby', 'Catto', 1, '9077993515', 'kcattos@photobucket.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (30, 36, 'Quinlan', 'Condell', 1, '6984313315', 'qcondellt@nytimes.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (31, 31, 'Goraud', 'Devenport', 1, '4053789531', 'gdevenportu@java.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (32, 39, 'Margaretha', 'Spafford', 1, '4462587613', 'mspaffordv@livejournal.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (33, 38, 'Emmie', 'Pashba', 1, '5053278869', 'epashbaw@examiner.com', 10, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (34, 38, 'Orelle', 'Redgewell', 1, '5429007882', 'oredgewellx@alibaba.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (35, 26, 'Isak', 'Hewertson', 1, '2604413607', 'ihewertsony@sakura.ne.jp', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (36, 27, 'Melissa', 'VanBrugh', 1, '3151043248', 'mvanbrughz@usatoday.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (37, 34, 'Phil', 'Cazin', 1, '7316945354', 'pcazin10@multiply.com', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (38, 50, 'Valry', 'Emanuelli', 1, '3419617982', 'vemanuelli11@t.co', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (39, 39, 'Sebastian', 'Biddle', 1, '9275116774', 'sbiddle12@prweb.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (40, 33, 'Jeanelle', 'Rook', 1, '3813285382', 'jrook13@usatoday.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (41, 46, 'Debee', 'Belitz', 1, '6504181327', 'dbelitz14@washingtonpost.com', 10, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (42, 30, 'Peggi', 'Kloster', 1, '2481319427', 'pkloster15@cmu.edu', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (43, 42, 'Gris', 'Wenderott', 1, '7985570433', 'gwenderott16@booking.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (44, 49, 'Rebekkah', 'Hauck', 1, '4239924581', 'rhauck17@godaddy.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (45, 45, 'Sibilla', 'Rushby', 1, '8185311551', 'srushby18@spiegel.de', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (46, 29, 'Trefor', 'Beet', 1, '7121669163', 'tbeet19@wired.com', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (47, 33, 'Waldo', 'Maunder', 1, '1182392915', 'wmaunder1a@cafepress.com', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (48, 41, 'Lonni', 'Dillinger', 1, '3216524084', 'ldillinger1b@bbc.co.uk', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (49, 34, 'Ray', 'Bartoszinski', 1, '9857934233', 'rbartoszinski1c@g.co', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (50, 30, 'Vonny', 'Tyhurst', 1, '8178901856', 'vtyhurst1d@fastcompany.com', 8, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (51, 50, 'Fabio', 'Conniam', 1, '9226718969', 'fconniam1e@webs.com', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (52, 40, 'Rebeka', 'Fellon', 1, '5206765257', 'rfellon1f@over-blog.com', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (53, 48, 'Camilla', 'Redhills', 1, '2174676993', 'credhills1g@jalbum.net', 6, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (54, 49, 'Jerrine', 'Legg', 1, '9033046863', 'jlegg1h@ucoz.com', 5, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (55, 44, 'Odelle', 'Berens', 1, '4819543083', 'oberens1i@berkeley.edu', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (56, 37, 'Abran', 'Reignolds', 1, '9192362452', 'areignolds1j@mtv.com', 10, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (57, 46, 'Errol', 'Lester', 1, '1586171038', 'elester1k@reuters.com', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (58, 25, 'Ad', 'Couve', 1, '7168905797', 'acouve1l@discovery.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (59, 26, 'Harrietta', 'McCord', 1, '5431112337', 'hmccord1m@diigo.com', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (60, 48, 'Florentia', 'Massow', 1, '8366626953', 'fmassow1n@exblog.jp', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (61, 36, 'Jaine', 'Emett', 1, '8538122203', 'jemett1o@dot.gov', 5, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (62, 42, 'Pattin', 'Pittet', 1, '5046843903', 'ppittet1p@so-net.ne.jp', 6, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (63, 37, 'Dareen', 'Mongeot', 1, '7982543044', 'dmongeot1q@biblegateway.com', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (64, 41, 'Kim', 'Loftus', 1, '8672154098', 'kloftus1r@columbia.edu', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (65, 29, 'Burtie', 'Drivers', 1, '7406180441', 'bdrivers1s@dedecms.com', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (66, 25, 'Mathian', 'Fretson', 1, '4813981202', 'mfretson1t@stanford.edu', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (67, 50, 'Clo', 'Whatson', 1, '2723644106', 'cwhatson1u@apache.org', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (68, 48, 'Reggie', 'Render', 1, '4802718236', 'rrender1v@fema.gov', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (69, 41, 'Milissent', 'Yakobowitz', 1, '2059665016', 'myakobowitz1w@joomla.org', 10, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (70, 29, 'Chester', 'Antonoyev', 1, '1963324687', 'cantonoyev1x@yolasite.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (71, 33, 'Pincus', 'Gannon', 1, '9106595939', 'pgannon1y@slate.com', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (72, 46, 'La verne', 'Pinshon', 1, '8839359927', 'lpinshon1z@narod.ru', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (73, 27, 'Antonella', 'Vinau', 1, '8393892639', 'avinau20@studiopress.com', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (74, 43, 'Cyndie', 'Isles', 1, '3508879617', 'cisles21@un.org', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (75, 39, 'Inesita', 'Lourenco', 1, '7844820913', 'ilourenco22@baidu.com', 10, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (76, 41, 'Nerita', 'Bubbings', 1, '3262763183', 'nbubbings23@macromedia.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (77, 40, 'Trev', 'Rous', 1, '9431051422', 'trous24@wikimedia.org', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (78, 45, 'Wilmar', 'Zuppa', 1, '5638622405', 'wzuppa25@tmall.com', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (79, 28, 'Ania', 'Hum', 1, '7402315296', 'ahum26@youtu.be', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (80, 40, 'Rosabel', 'Agglione', 1, '2526750686', 'ragglione27@huffingtonpost.com', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (81, 48, 'Gaspard', 'Thaw', 1, '1355519312', 'gthaw28@canalblog.com', 6, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (82, 43, 'Ed', 'Milam', 1, '6335165312', 'emilam29@bravesites.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (83, 38, 'Filip', 'Vonasek', 1, '8948971617', 'fvonasek2a@myspace.com', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (84, 42, 'Kali', 'Popham', 1, '3753866491', 'kpopham2b@example.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (85, 38, 'Wainwright', 'Brinkworth', 1, '5261345372', 'wbrinkworth2c@ed.gov', 6, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (86, 38, 'Gisella', 'Seacombe', 1, '4395891636', 'gseacombe2d@walmart.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (87, 47, 'Franni', 'Bulfoy', 1, '4151927494', 'fbulfoy2e@theatlantic.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (88, 26, 'Tildy', 'Grandison', 1, '9865366011', 'tgrandison2f@ftc.gov', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (89, 34, 'Lucien', 'Huscroft', 1, '7337072736', 'lhuscroft2g@cbc.ca', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (90, 28, 'Frederico', 'Chattock', 1, '3418271885', 'fchattock2h@intel.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (91, 45, 'Johnathon', 'Pawels', 1, '7488556042', 'jpawels2i@trellian.com', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (92, 34, 'Patrick', 'Haggata', 1, '8498065336', 'phaggata2j@oakley.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (93, 28, 'Leoline', 'Wykey', 1, '9583386762', 'lwykey2k@blogtalkradio.com', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (94, 31, 'Rustin', 'Chanson', 1, '7039432219', 'rchanson2l@google.ca', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (95, 26, 'Mignon', 'Way', 1, '6965812092', 'mway2m@usnews.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (96, 44, 'Tull', 'Clifforth', 1, '7577040204', 'tclifforth2n@sbwire.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (97, 46, 'Maisie', 'Dulling', 1, '8072066741', 'mdulling2o@marketwatch.com', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (98, 30, 'Brantley', 'Shephard', 1, '3528923652', 'bshephard2p@alexa.com', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (99, 34, 'Gibb', 'Danigel', 1, '8881189819', 'gdanigel2q@discovery.com', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (100, 42, 'Silva', 'Ramas', 1, '4464071288', 'sramas2r@people.com.cn', 1, 'Not Available');
