create table service_men (
	id INT,
	age INT,
	name VARCHAR(50),
	serv_id INT,
	phone_no VARCHAR(50),
	work_experience INT,
	availability VARCHAR(13)
);
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (1, 28, 'Gates Dinan', 1, '9018264178', 1, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (2, 39, 'Benedetto Spanton', 1, '6926376947', 1, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (3, 37, 'Leilah Mineghelli', 1, '3127239747', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (4, 42, 'Amelina Bertomieu', 1, '2584233003', 1, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (5, 28, 'Lenee Van de Castele', 1, '2667465352', 7, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (6, 39, 'Selene Lavelle', 1, '7453602786', 5, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (7, 45, 'Merle Apdell', 1, '8946331742', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (8, 43, 'Lou Whitmore', 1, '6308321456', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (9, 25, 'Guillermo Daudray', 1, '7296740777', 4, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (10, 50, 'Krispin Mottinelli', 1, '8025127662', 3, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (11, 30, 'Lenette Cooke', 1, '9033631682', 10, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (12, 27, 'Korrie Jagger', 1, '5068436903', 6, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (13, 45, 'Arv Cammoile', 1, '9761365178', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (14, 31, 'Florenza Mosdall', 1, '4564456845', 2, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (15, 39, 'Tuesday Kimblen', 1, '8287300671', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (16, 26, 'Janella Clemenzo', 1, '8423784347', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (17, 25, 'Kellyann Shwenn', 1, '5955801087', 10, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (18, 49, 'Valentino Batthew', 1, '8358334181', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (19, 35, 'Merrilee Mushrow', 1, '1705927474', 10, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (20, 49, 'Jayne Jahner', 1, '9625967788', 2, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (21, 42, 'Whitby Faircley', 1, '8578632739', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (22, 33, 'Lusa Truter', 1, '3292383369', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (23, 30, 'Chrissy Ciardo', 1, '6414125520', 1, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (24, 46, 'Levey Murrthum', 1, '4732266209', 8, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (25, 27, 'Willey Imms', 1, '6307025367', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (26, 38, 'Chet Chelsom', 1, '7223036881', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (27, 29, 'Ninetta Dredge', 1, '2386874750', 10, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (28, 28, 'Craggie Veazey', 1, '8312253003', 4, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (29, 25, 'Elene Burrage', 1, '2427746168', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (30, 30, 'Manya Siward', 1, '8629743813', 3, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (31, 45, 'Trip Merryweather', 1, '3574565020', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (32, 27, 'Bibby Beetham', 1, '8593755773', 10, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (33, 36, 'Iseabal Paulsson', 1, '1483700929', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (34, 37, 'Nicholle Allwright', 1, '5665798662', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (35, 44, 'Pammy Hawken', 1, '4753319763', 2, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (36, 46, 'Rog Murdie', 1, '4369475667', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (37, 31, 'Nola Coyish', 1, '4466556945', 3, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (38, 25, 'Rosalyn Bramford', 1, '5946765273', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (39, 44, 'Laetitia Idle', 1, '1839563276', 4, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (40, 34, 'Fin Joslyn', 1, '7392319818', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (41, 36, 'Bernardina Maudlen', 1, '2372277075', 4, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (42, 47, 'Wald Reyne', 1, '3865199954', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (43, 30, 'Boot Godilington', 1, '3115148471', 7, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (44, 47, 'Pren Hugill', 1, '6952523862', 2, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (45, 36, 'Frants Henriques', 1, '5978485593', 3, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (46, 42, 'Calhoun Zanettini', 1, '9138794064', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (47, 35, 'Quinn Roizin', 1, '7307015450', 7, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (48, 38, 'Jen Daintree', 1, '7051978390', 7, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (49, 36, 'Pippy Setch', 1, '3714859250', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (50, 29, 'Gretal Sarvar', 1, '2755823919', 2, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (51, 33, 'Fredia Boynes', 1, '7496123796', 5, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (52, 50, 'Vina Camacke', 1, '3894109969', 6, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (53, 44, 'Howie Kain', 1, '2373425001', 1, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (54, 34, 'Karole Hakonsson', 1, '3742111665', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (55, 42, 'Leisha Le Merchant', 1, '5146768971', 6, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (56, 31, 'Clementine Scamadine', 1, '2553898844', 1, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (57, 27, 'Barnabas Janko', 1, '4289293783', 6, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (58, 32, 'Zahara Mewis', 1, '5202225339', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (59, 25, 'Annelise Raden', 1, '5574237554', 3, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (60, 30, 'Noel Wrintmore', 1, '5488057336', 8, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (61, 30, 'Kristo Longbothom', 1, '7343277189', 3, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (62, 25, 'Damian Juniper', 1, '5541494679', 6, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (63, 31, 'Goldi Caveney', 1, '8703717693', 8, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (64, 43, 'Sari Rowlinson', 1, '4119289547', 3, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (65, 27, 'Haywood Flannigan', 1, '4479407696', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (66, 26, 'Tiffany Fantini', 1, '6845922540', 8, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (67, 47, 'Sibella Tottem', 1, '8903256487', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (68, 28, 'Bevan McCarly', 1, '9055566785', 1, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (69, 42, 'Rosina Arsmith', 1, '4681649300', 7, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (70, 28, 'Sarina Pulford', 1, '9438860120', 7, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (71, 49, 'Cirilo Rapley', 1, '7111307623', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (72, 35, 'Janene Digle', 1, '5096118746', 1, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (73, 27, 'Kirsti Sharphurst', 1, '1909983439', 6, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (74, 44, 'Clevie Coursor', 1, '4094027362', 2, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (75, 38, 'Jeanine Amthor', 1, '7123605041', 9, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (76, 44, 'Woodman Dewes', 1, '5123856400', 3, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (77, 41, 'Cly Wabersich', 1, '2803839760', 4, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (78, 45, 'Kelcie Busch', 1, '7692336303', 3, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (79, 49, 'Sancho Giovanizio', 1, '2167275584', 5, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (80, 49, 'Paule Stainton', 1, '4357699441', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (81, 45, 'Jennee Murrthum', 1, '9589120063', 6, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (82, 36, 'Ashton Baiss', 1, '3796589268', 10, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (83, 47, 'Stormi Sewall', 1, '7198467802', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (84, 41, 'Trumann Cubberley', 1, '1006333486', 4, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (85, 33, 'Steffie Daverin', 1, '7372172632', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (86, 50, 'Stanfield Tomblett', 1, '1975919925', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (87, 32, 'Janice Whiteside', 1, '4806733012', 10, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (88, 34, 'Karrie Echalie', 1, '2158002403', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (89, 49, 'Gisella Fluck', 1, '7351100153', 2, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (90, 26, 'Nahum Happert', 1, '1813440816', 1, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (91, 38, 'Mead Dallewater', 1, '1788945582', 10, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (92, 41, 'Victor Wilkenson', 1, '3796256141', 3, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (93, 50, 'Maryjo Devany', 1, '1098090560', 6, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (94, 39, 'Torrence Louder', 1, '3699601948', 8, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (95, 34, 'Riordan Madgwick', 1, '8347046405', 7, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (96, 27, 'Illa Corps', 1, '4675568249', 8, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (97, 32, 'Grenville Casaro', 1, '4551757969', 4, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (98, 40, 'Simon Disdel', 1, '1756719774', 5, 'Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (99, 40, 'Estele Knill', 1, '4099661363', 9, 'Not Available');
insert into service_men (id, age, name, serv_id, phone_no, work_experience, availability) values (100, 31, 'Moore Peckett', 1, '4817011600', 2, 'Not Available');
