create table service_men (
	id INT,
	age INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	service_id INT,
	phone_no VARCHAR(50),
	email VARCHAR(50),
	work_experience INT,
	availability VARCHAR(13)
);
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (1, 32, 'Pinchas', 'Bruna', 4, '5617306582', 'pbruna0@craigslist.org', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (2, 27, 'Erminia', 'Skym', 1, '5087964155', 'eskym1@pagesperso-orange.fr', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (3, 33, 'Jonie', 'Thorn', 3, '3101138142', 'jthorn2@goo.gl', 10, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (4, 30, 'Francisca', 'Feehely', 3, '3681765968', 'ffeehely3@51.la', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (5, 45, 'Corrinne', 'Di Carlo', 2, '9689826871', 'cdicarlo4@godaddy.com', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (6, 36, 'Abigale', 'Edmonstone', 1, '2189259840', 'aedmonstone5@ebay.co.uk', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (7, 50, 'Archibald', 'Drew-Clifton', 4, '9937549878', 'adrewclifton6@gmpg.org', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (8, 29, 'Anna-diane', 'Lutsch', 3, '6549956409', 'alutsch7@unicef.org', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (9, 29, 'Megan', 'Robjohns', 2, '6528170264', 'mrobjohns8@twitpic.com', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (10, 27, 'Brody', 'McLanachan', 3, '9668140660', 'bmclanachan9@techcrunch.com', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (11, 26, 'Ware', 'Grasner', 3, '1362777079', 'wgrasnera@youtu.be', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (12, 47, 'Etta', 'Darling', 4, '6626290911', 'edarlingb@nbcnews.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (13, 31, 'Audrye', 'Calbreath', 1, '4731271314', 'acalbreathc@bloglines.com', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (14, 50, 'Hermon', 'Creelman', 3, '4715210482', 'hcreelmand@tmall.com', 5, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (15, 50, 'Fidelia', 'Estable', 3, '5852019980', 'festablee@bbc.co.uk', 10, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (16, 40, 'Barde', 'Colisbe', 1, '3889104633', 'bcolisbef@behance.net', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (17, 37, 'Mara', 'Gypson', 4, '9292543601', 'mgypsong@infoseek.co.jp', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (18, 34, 'Joell', 'Ostrich', 3, '6484792553', 'jostrichh@de.vu', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (19, 26, 'Adolf', 'Bourcq', 2, '3483066666', 'abourcqi@usa.gov', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (20, 29, 'Abigael', 'Pretsell', 3, '7983206228', 'apretsellj@salon.com', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (21, 33, 'Petronella', 'Blankett', 4, '6843612999', 'pblankettk@yahoo.co.jp', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (22, 46, 'Scot', 'Zukerman', 3, '6711079250', 'szukermanl@cbslocal.com', 6, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (23, 44, 'Lawry', 'Trammel', 4, '7625881472', 'ltrammelm@mac.com', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (24, 35, 'Miriam', 'Chattell', 3, '8086895034', 'mchattelln@cbslocal.com', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (25, 30, 'Ev', 'Giovannoni', 3, '3028006004', 'egiovannonio@last.fm', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (26, 33, 'Cati', 'Orringe', 3, '2922559883', 'corringep@usda.gov', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (27, 39, 'Cullin', 'Ormistone', 1, '8419079097', 'cormistoneq@samsung.com', 10, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (28, 33, 'Rosetta', 'Waddoups', 3, '4062687263', 'rwaddoupsr@xrea.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (29, 28, 'Elsy', 'Bodker', 3, '4513904452', 'ebodkers@artisteer.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (30, 42, 'Tiena', 'Tedman', 3, '1183507571', 'ttedmant@taobao.com', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (31, 50, 'Robinet', 'Pryn', 4, '2107804380', 'rprynu@examiner.com', 5, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (32, 37, 'Reamonn', 'MacDavitt', 3, '1658324571', 'rmacdavittv@ox.ac.uk', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (33, 27, 'Allissa', 'Ryland', 2, '1035858687', 'arylandw@ehow.com', 10, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (34, 47, 'Benito', 'Kingaby', 4, '6934313014', 'bkingabyx@si.edu', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (35, 33, 'Leopold', 'Tabard', 1, '9577879180', 'ltabardy@mlb.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (36, 48, 'Legra', 'Bertson', 2, '6331358908', 'lbertsonz@github.io', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (37, 44, 'Dani', 'Wickins', 2, '2842170485', 'dwickins10@cam.ac.uk', 8, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (38, 40, 'Kingsley', 'O''Daly', 3, '1327682757', 'kodaly11@tumblr.com', 8, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (39, 40, 'Nigel', 'Tuxell', 1, '9391247748', 'ntuxell12@upenn.edu', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (40, 31, 'Alan', 'Scane', 3, '6829648240', 'ascane13@usnews.com', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (41, 41, 'Guido', 'Sibbit', 4, '6613214836', 'gsibbit14@cisco.com', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (42, 43, 'Domini', 'Domelaw', 2, '1532060985', 'ddomelaw15@com.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (43, 38, 'Archibaldo', 'Christie', 2, '1733515083', 'achristie16@alexa.com', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (44, 44, 'Jacquie', 'Speere', 4, '2551576921', 'jspeere17@jimdo.com', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (45, 33, 'Lorant', 'Van Baaren', 1, '5178856878', 'lvanbaaren18@hao123.com', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (46, 40, 'Hildagarde', 'Liver', 2, '6606620825', 'hliver19@wsj.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (47, 40, 'Gav', 'Izhak', 4, '6395508043', 'gizhak1a@usatoday.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (48, 40, 'Elnore', 'Marcus', 4, '1705119719', 'emarcus1b@yellowpages.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (49, 39, 'Bartel', 'Ferroli', 2, '2366231356', 'bferroli1c@nature.com', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (50, 33, 'Sharon', 'Phoebe', 1, '7595831908', 'sphoebe1d@hao123.com', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (51, 41, 'Miltie', 'Kermannes', 1, '9002577783', 'mkermannes1e@dell.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (52, 39, 'Lyn', 'O''Sullivan', 3, '9303200178', 'losullivan1f@nifty.com', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (53, 41, 'Crichton', 'Caccavale', 2, '7257869267', 'ccaccavale1g@behance.net', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (54, 27, 'Jennica', 'Skurray', 2, '3151953135', 'jskurray1h@sohu.com', 8, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (55, 30, 'Nikkie', 'Tatam', 2, '7633479752', 'ntatam1i@forbes.com', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (56, 37, 'Averil', 'Oxe', 3, '8627461896', 'aoxe1j@acquirethisname.com', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (57, 30, 'Car', 'Smitherman', 1, '5394228563', 'csmitherman1k@unblog.fr', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (58, 48, 'Dag', 'Illidge', 4, '2567046408', 'dillidge1l@networkadvertising.org', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (59, 32, 'Austine', 'Coners', 4, '8251391136', 'aconers1m@mozilla.org', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (60, 25, 'Bobinette', 'Fallows', 2, '8599304002', 'bfallows1n@addthis.com', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (61, 41, 'Marta', 'Lardier', 3, '5452932744', 'mlardier1o@netvibes.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (62, 26, 'Waylon', 'Wooland', 3, '9729684313', 'wwooland1p@xing.com', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (63, 45, 'Corene', 'Yole', 2, '7527463943', 'cyole1q@yahoo.co.jp', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (64, 46, 'Filide', 'Lackham', 2, '1033751992', 'flackham1r@de.vu', 1, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (65, 44, 'Fredek', 'Cotty', 4, '6003660242', 'fcotty1s@jigsy.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (66, 42, 'Debby', 'Vell', 1, '8963599713', 'dvell1t@geocities.jp', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (67, 36, 'Prissie', 'Pascho', 2, '3367419768', 'ppascho1u@rakuten.co.jp', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (68, 36, 'Bartlett', 'Martelet', 1, '5288159105', 'bmartelet1v@shareasale.com', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (69, 29, 'Ingmar', 'Deakins', 4, '4612221891', 'ideakins1w@is.gd', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (70, 26, 'Casar', 'Garrit', 3, '3325783937', 'cgarrit1x@godaddy.com', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (71, 38, 'Kim', 'Daborne', 3, '4182105753', 'kdaborne1y@ebay.co.uk', 2, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (72, 40, 'Nichole', 'Shefton', 2, '8095459977', 'nshefton1z@t.co', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (73, 29, 'Fabiano', 'Wilkie', 4, '9726341736', 'fwilkie20@ted.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (74, 27, 'Gale', 'Ekless', 4, '7545039363', 'gekless21@wix.com', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (75, 33, 'Mady', 'Cheyenne', 2, '2574502580', 'mcheyenne22@salon.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (76, 50, 'Phylis', 'Cowthart', 1, '6778485160', 'pcowthart23@scribd.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (77, 48, 'Frans', 'Songhurst', 1, '9591312962', 'fsonghurst24@slideshare.net', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (78, 25, 'Em', 'Standen', 1, '2542299507', 'estanden25@senate.gov', 9, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (79, 40, 'Rozanna', 'Culverhouse', 4, '4345866744', 'rculverhouse26@whitehouse.gov', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (80, 44, 'Cooper', 'Northridge', 1, '5107147950', 'cnorthridge27@pagesperso-orange.fr', 7, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (81, 43, 'Bart', 'Ferrierio', 3, '9025653000', 'bferrierio28@flickr.com', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (82, 39, 'Gottfried', 'Quilleash', 1, '3965446876', 'gquilleash29@soundcloud.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (83, 29, 'Romy', 'Wilman', 1, '8577611783', 'rwilman2a@blog.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (84, 48, 'Alric', 'Ashwood', 1, '8805146497', 'aashwood2b@woothemes.com', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (85, 32, 'Caryl', 'Sarath', 1, '2158309274', 'csarath2c@wix.com', 4, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (86, 35, 'Adelbert', 'Mervyn', 2, '2683167930', 'amervyn2d@arstechnica.com', 8, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (87, 30, 'Paule', 'Billanie', 3, '1602175578', 'pbillanie2e@netvibes.com', 1, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (88, 36, 'Penni', 'O''Dowling', 4, '6178130449', 'podowling2f@drupal.org', 10, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (89, 32, 'Emmalee', 'Gerbel', 4, '7764514202', 'egerbel2g@alexa.com', 3, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (90, 40, 'Robin', 'Edmund', 2, '8857527656', 'redmund2h@paypal.com', 5, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (91, 46, 'Jervis', 'Poag', 3, '3316848416', 'jpoag2i@github.io', 5, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (92, 40, 'Reyna', 'Danilevich', 3, '4122175291', 'rdanilevich2j@usnews.com', 2, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (93, 38, 'Pavia', 'Antcliff', 1, '9072456813', 'pantcliff2k@upenn.edu', 6, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (94, 33, 'Norrie', 'Fedynski', 2, '8586523563', 'nfedynski2l@liveinternet.ru', 4, 'Not Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (95, 46, 'Viviyan', 'Lamp', 1, '1054919088', 'vlamp2m@prnewswire.com', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (96, 40, 'Odessa', 'Macken', 1, '4249357302', 'omacken2n@google.pl', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (97, 29, 'Franklyn', 'Muslim', 4, '3485137713', 'fmuslim2o@paypal.com', 9, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (98, 44, 'Rudd', 'Burl', 2, '1049073036', 'rburl2p@icio.us', 3, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (99, 29, 'Noreen', 'Sherbrook', 4, '9019235697', 'nsherbrook2q@guardian.co.uk', 7, 'Available');
insert into service_men (id, age, first_name, last_name, service_id, phone_no, email, work_experience, availability) values (100, 38, 'Tallie', 'Chatburn', 4, '6186743145', 'tchatburn2r@360.cn', 2, 'Available');
