create table service_men (
	id INT,
	age INT,
	name VARCHAR(50),
	service_id INT,
	contact_no VARCHAR(50),
	work_experience INT,
	availability VARCHAR(13)
);
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (1, 44, 'Erinn Crumbleholme', 1, '5368597482', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (2, 44, 'Catriona Robertsen', 1, '3097048258', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (3, 29, 'Cathie Lidington', 1, '9435167748', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (4, 32, 'Merrile Sigg', 1, '2545617905', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (5, 39, 'Terrence McCray', 1, '3141398785', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (6, 30, 'Niall Bonett', 1, '1947918849', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (7, 34, 'Krysta Chatan', 1, '7034563667', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (8, 34, 'Tye Titta', 1, '5142420497', 2, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (9, 42, 'Chico Triplet', 1, '1781650399', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (10, 45, 'Humberto Ibbeson', 1, '3977013108', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (11, 40, 'Loydie Bozworth', 1, '8646093070', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (12, 38, 'Clayson Shellsheere', 1, '6437339832', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (13, 29, 'Bevon Bassford', 1, '5958834475', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (14, 35, 'Shell Hasley', 1, '6311075605', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (15, 39, 'Calypso Giacovelli', 1, '1089062929', 6, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (16, 35, 'Leanna Joinson', 1, '9919346746', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (17, 50, 'Alec Lancashire', 1, '6977944022', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (18, 48, 'Cherri Gerhts', 1, '5561937373', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (19, 29, 'Thorn Bagshawe', 1, '9206848125', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (20, 32, 'Gabriello Crowcher', 1, '9665425049', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (21, 27, 'Lorie Brunicke', 1, '5201459181', 9, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (22, 35, 'Lowe Brizland', 1, '8181981497', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (23, 46, 'Danila Francom', 1, '7484042560', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (24, 49, 'Winny Paget', 1, '3962590085', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (25, 32, 'Gates Alexsandrovich', 1, '1313648341', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (26, 36, 'Anna Prangley', 1, '7224695656', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (27, 25, 'Cornell Mersh', 1, '8389893752', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (28, 27, 'Eddie Rudland', 1, '6567024406', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (29, 44, 'Aharon Lantry', 1, '6229454268', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (30, 42, 'Tobiah Blankman', 1, '8834494224', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (31, 27, 'Art O''Rafferty', 1, '4632853719', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (32, 25, 'Della Callar', 1, '4954176419', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (33, 32, 'Cally Zukierman', 1, '8535693437', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (34, 41, 'Isak Duffit', 1, '8775328310', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (35, 43, 'Annabal Cliffe', 1, '9641528382', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (36, 38, 'Charles Tomala', 1, '5149972705', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (37, 28, 'Cirstoforo Spavon', 1, '4727228060', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (38, 39, 'Rickey Powers', 1, '6969772630', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (39, 47, 'Mela Morter', 1, '6745314650', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (40, 33, 'Diannne Blagden', 1, '3393128718', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (41, 25, 'Hodge Calendar', 1, '4041450934', 9, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (42, 48, 'Charley Hegdonne', 1, '8382550456', 9, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (43, 42, 'Ax McCunn', 1, '5777513156', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (44, 32, 'Valene Trewman', 1, '1422064218', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (45, 39, 'Allin Imorts', 1, '1118310149', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (46, 33, 'Deedee Rodenburgh', 1, '4761759165', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (47, 47, 'Katie Gisbye', 1, '6346086635', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (48, 28, 'Grata Greenstreet', 1, '1017486116', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (49, 37, 'Almire Klaggeman', 1, '7514213573', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (50, 34, 'Mair Hinemoor', 1, '2824683734', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (51, 43, 'Lynelle Rooper', 1, '3394975845', 6, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (52, 26, 'Hanan Trousdale', 1, '8723627901', 5, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (53, 35, 'Jeannie Rohloff', 1, '2504513014', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (54, 40, 'Emyle Gini', 1, '7684151058', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (55, 46, 'Alvera Desesquelle', 1, '6356288349', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (56, 41, 'Antonie Fosbraey', 1, '8206628738', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (57, 42, 'Tova Boskell', 1, '2656942039', 9, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (58, 34, 'Traver Le Barre', 1, '9925576106', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (59, 50, 'Mariejeanne Ecclestone', 1, '6024998806', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (60, 40, 'Nick Grishagin', 1, '7326697275', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (61, 34, 'Alvie Selwyn', 1, '6388489123', 6, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (62, 45, 'Margarete Bolsover', 1, '5415638516', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (63, 28, 'Marlowe Ollis', 1, '9795968952', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (64, 32, 'Lissi Gann', 1, '6893611740', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (65, 36, 'Deanne Creedland', 1, '7163206482', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (66, 40, 'Stanislas Baiyle', 1, '1055326419', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (67, 46, 'Crista Nardi', 1, '2625220087', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (68, 25, 'Florance Havile', 1, '5465524925', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (69, 47, 'Ann Blackah', 1, '8792178432', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (70, 47, 'Philippa Orans', 1, '1725150620', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (71, 47, 'Jasper Costanza', 1, '8096779179', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (72, 45, 'Tine Gatward', 1, '6012125838', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (73, 43, 'Jordain Basindale', 1, '8795211756', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (74, 36, 'Dickie Petrolli', 1, '3975506304', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (75, 48, 'Madlen Oleszkiewicz', 1, '6073851531', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (76, 42, 'Jandy Dunning', 1, '6703764731', 3, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (77, 46, 'Anson Itzhaiek', 1, '8993908266', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (78, 42, 'Laurel Chaston', 1, '5373583947', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (79, 41, 'Starlin Clint', 1, '9077129137', 2, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (80, 39, 'Myron Heffy', 1, '9801053200', 10, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (81, 28, 'Karl Pimerick', 1, '1901936709', 4, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (82, 29, 'Saunder June', 1, '3356360806', 1, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (83, 32, 'Elspeth Petrie', 1, '9808720009', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (84, 49, 'Cecily Fells', 1, '6219871647', 1, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (85, 26, 'Wendall Pert', 1, '9236286139', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (86, 46, 'Constance Beynke', 1, '1891786065', 4, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (87, 42, 'Saudra Milkins', 1, '4733769287', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (88, 37, 'Gilberte Wareing', 1, '4841646984', 3, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (89, 36, 'Andee McFadzean', 1, '8672233062', 6, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (90, 43, 'Jinny Mangan', 1, '8792708026', 6, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (91, 47, 'Fleur Lubomirski', 1, '8162742421', 9, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (92, 42, 'Tom Curzey', 1, '2637386214', 7, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (93, 29, 'Newton Roch', 1, '1212918475', 7, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (94, 42, 'Hastie Ferrand', 1, '8237422960', 8, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (95, 42, 'Brandise Saph', 1, '2275571148', 7, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (96, 46, 'Catha Demcak', 1, '6425054324', 6, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (97, 35, 'Georgie Keford', 1, '5435937111', 5, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (98, 48, 'Agnella Frankes', 1, '1129573987', 10, 'Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (99, 28, 'Jonah Beharrell', 1, '9287705005', 8, 'Not Available');
insert into service_men (id, age, name, service_id, contact_no, work_experience, availability) values (100, 26, 'Kalina Castella', 1, '6712872542', 2, 'Available');
