create table service_men (
	id INT,
	age INT,
	name VARCHAR(50),
	service_id INT,
	phone_no VARCHAR(50),
	email VARCHAR(50),
	work_experience INT,
	availability VARCHAR(13)
);
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (1, 28, 'Alma Kearey', 1, '3821993626', 'akearey0@vinaora.com', 1, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (2, 40, 'Rhodie Shemelt', 1, '7721079813', 'rshemelt1@yellowbook.com', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (3, 31, 'Venus Smallpiece', 1, '6419596292', 'vsmallpiece2@spotify.com', 10, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (4, 31, 'Cristin Cator', 1, '4336433945', 'ccator3@wisc.edu', 3, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (5, 26, 'Lowe Shone', 1, '7176139108', 'lshone4@loc.gov', 5, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (6, 25, 'Alejoa Benedict', 1, '5937495114', 'abenedict5@gnu.org', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (7, 45, 'Brantley Winch', 1, '2664306357', 'bwinch6@cpanel.net', 9, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (8, 30, 'Cybill Vassay', 1, '5459636360', 'cvassay7@taobao.com', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (9, 32, 'Cob Hollows', 1, '6282604761', 'chollows8@wired.com', 8, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (10, 29, 'Chase Oxtiby', 1, '3052295176', 'coxtiby9@free.fr', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (11, 46, 'Hyacinth Torrans', 1, '5001100759', 'htorransa@timesonline.co.uk', 7, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (12, 34, 'Duky Bansal', 1, '3665820477', 'dbansalb@de.vu', 4, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (13, 37, 'Emlyn Osgar', 1, '2269716697', 'eosgarc@reverbnation.com', 6, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (14, 50, 'Clair Rames', 1, '3329814405', 'cramesd@omniture.com', 10, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (15, 27, 'Gustie Braidford', 1, '1248911420', 'gbraidforde@netlog.com', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (16, 46, 'Ralf Weson', 1, '8381548982', 'rwesonf@eepurl.com', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (17, 33, 'Gretal Thundercliffe', 1, '3461224002', 'gthundercliffeg@uiuc.edu', 3, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (18, 42, 'Sukey Tunder', 1, '4308990116', 'stunderh@ifeng.com', 9, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (19, 45, 'Terrye Edgerton', 1, '6359844272', 'tedgertoni@qq.com', 10, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (20, 26, 'Annabell Tudhope', 1, '2764904687', 'atudhopej@hatena.ne.jp', 7, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (21, 42, 'Jayne Jirasek', 1, '6568841783', 'jjirasekk@jugem.jp', 6, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (22, 25, 'Alikee Werndley', 1, '9644740339', 'awerndleyl@mapy.cz', 1, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (23, 46, 'Asia Bezemer', 1, '6525751258', 'abezemerm@indiatimes.com', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (24, 46, 'Amitie Devlin', 1, '3961682724', 'adevlinn@theglobeandmail.com', 4, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (25, 48, 'Tabbitha Cathee', 1, '1278588259', 'tcatheeo@gravatar.com', 8, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (26, 38, 'Mara Admans', 1, '7831653817', 'madmansp@blogs.com', 3, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (27, 26, 'Ernie Telezhkin', 1, '3359780595', 'etelezhkinq@comsenz.com', 3, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (28, 32, 'Lucille Ventura', 1, '8176441439', 'lventurar@examiner.com', 6, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (29, 42, 'Glad Humbert', 1, '9461913750', 'ghumberts@example.com', 3, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (30, 50, 'Ranee Greatrex', 1, '8294213178', 'rgreatrext@google.de', 4, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (31, 45, 'Sergei Birmingham', 1, '7308785298', 'sbirminghamu@wired.com', 1, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (32, 31, 'Galven Pady', 1, '6794636018', 'gpadyv@usnews.com', 6, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (33, 47, 'Debor Mussolini', 1, '2261472705', 'dmussoliniw@fema.gov', 9, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (34, 48, 'Pierce Humber', 1, '7383111434', 'phumberx@livejournal.com', 4, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (35, 25, 'Bearnard Riseborough', 1, '5832900247', 'briseboroughy@last.fm', 7, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (36, 49, 'Kalle Saladin', 1, '4206798251', 'ksaladinz@bigcartel.com', 10, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (37, 49, 'Mohammed Schach', 1, '1292574361', 'mschach10@google.com.au', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (38, 33, 'Casey Blowing', 1, '1982544148', 'cblowing11@networkadvertising.org', 6, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (39, 28, 'Thorstein Bakeup', 1, '4849113955', 'tbakeup12@typepad.com', 10, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (40, 47, 'Theodoric Masding', 1, '1232416236', 'tmasding13@home.pl', 3, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (41, 47, 'Karel Isacoff', 1, '9185041540', 'kisacoff14@sohu.com', 6, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (42, 50, 'Dudley Ferne', 1, '1994106917', 'dferne15@flavors.me', 4, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (43, 38, 'Arda Dederick', 1, '5319531016', 'adederick16@icq.com', 8, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (44, 45, 'Coreen Hebson', 1, '8757577324', 'chebson17@nyu.edu', 5, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (45, 36, 'Rourke Marling', 1, '7574732182', 'rmarling18@sourceforge.net', 9, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (46, 37, 'Dodie Millership', 1, '1572771343', 'dmillership19@lycos.com', 8, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (47, 31, 'Cherilynn Ingerson', 1, '9831391128', 'cingerson1a@china.com.cn', 10, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (48, 48, 'Guthrie Whooley', 1, '9825073721', 'gwhooley1b@liveinternet.ru', 10, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (49, 44, 'Arnoldo Chainey', 1, '6059040262', 'achainey1c@addthis.com', 8, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (50, 32, 'Tamqrah Brixey', 1, '5607129620', 'tbrixey1d@goodreads.com', 8, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (51, 40, 'Port Connell', 1, '6375200311', 'pconnell1e@java.com', 3, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (52, 49, 'Brina O''Gleasane', 1, '1117406452', 'bogleasane1f@nymag.com', 7, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (53, 43, 'Andromache Eccleston', 1, '9042028684', 'aeccleston1g@wordpress.com', 2, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (54, 48, 'Billy Napper', 1, '1392240210', 'bnapper1h@nps.gov', 2, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (55, 26, 'Prisca Carragher', 1, '7209506701', 'pcarragher1i@canalblog.com', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (56, 50, 'Carri Purdie', 1, '7264915766', 'cpurdie1j@liveinternet.ru', 7, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (57, 47, 'Alexis Haddick', 1, '6734060221', 'ahaddick1k@ifeng.com', 5, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (58, 44, 'Lenora Trippick', 1, '5609811229', 'ltrippick1l@cloudflare.com', 8, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (59, 33, 'Eveline Denman', 1, '7157347626', 'edenman1m@nasa.gov', 2, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (60, 35, 'Trey Camble', 1, '6893929623', 'tcamble1n@nytimes.com', 2, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (61, 35, 'Ethelbert Denerley', 1, '1658805080', 'edenerley1o@va.gov', 9, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (62, 32, 'Torrance McLice', 1, '3853236396', 'tmclice1p@list-manage.com', 8, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (63, 37, 'Zsa zsa Brendish', 1, '8575855631', 'zzsa1q@sciencedaily.com', 9, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (64, 26, 'Elvin Cubberley', 1, '9728081032', 'ecubberley1r@youku.com', 4, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (65, 41, 'Kelbee Rozenbaum', 1, '6267576124', 'krozenbaum1s@w3.org', 2, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (66, 30, 'Kinsley Forkan', 1, '6539408438', 'kforkan1t@canalblog.com', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (67, 45, 'Noellyn Pollock', 1, '4059305661', 'npollock1u@yolasite.com', 1, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (68, 27, 'Beale de Quesne', 1, '6983579397', 'bde1v@blogspot.com', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (69, 34, 'Ninetta Charlet', 1, '8837090283', 'ncharlet1w@mysql.com', 9, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (70, 26, 'Anette Ivantsov', 1, '6562584911', 'aivantsov1x@mapy.cz', 3, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (71, 40, 'Madison Riall', 1, '8052955039', 'mriall1y@mapquest.com', 8, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (72, 34, 'Blake Tethcote', 1, '8752275836', 'btethcote1z@salon.com', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (73, 37, 'Saloma Scrowston', 1, '5672584324', 'sscrowston20@github.io', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (74, 47, 'Lynnet Wisby', 1, '1306247290', 'lwisby21@harvard.edu', 5, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (75, 25, 'Hadlee Underdown', 1, '2474310267', 'hunderdown22@blogtalkradio.com', 9, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (76, 26, 'Horatius Lepoidevin', 1, '7079117973', 'hlepoidevin23@nationalgeographic.com', 2, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (77, 29, 'Wilt Leckenby', 1, '8455883088', 'wleckenby24@digg.com', 2, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (78, 28, 'Ortensia Mitchenson', 1, '2095786398', 'omitchenson25@simplemachines.org', 4, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (79, 44, 'Eleen Pagelsen', 1, '3282763982', 'epagelsen26@wired.com', 5, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (80, 29, 'Harvey Neilus', 1, '2507242208', 'hneilus27@sogou.com', 5, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (81, 38, 'Kikelia Henniger', 1, '3596014017', 'khenniger28@nps.gov', 9, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (82, 36, 'Meridith Ruusa', 1, '8055510225', 'mruusa29@chron.com', 4, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (83, 35, 'Sybil Arnaudin', 1, '1042650870', 'sarnaudin2a@freewebs.com', 6, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (84, 29, 'Irwin Simon', 1, '8861088985', 'isimon2b@tamu.edu', 10, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (85, 47, 'Evered Blissitt', 1, '9074894706', 'eblissitt2c@51.la', 4, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (86, 38, 'Matthiew Winley', 1, '3982177527', 'mwinley2d@blogger.com', 1, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (87, 28, 'Ilyse Sail', 1, '2341337496', 'isail2e@instagram.com', 7, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (88, 43, 'Jarid Stummeyer', 1, '7202073289', 'jstummeyer2f@cdbaby.com', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (89, 27, 'Marinna Cake', 1, '7222126391', 'mcake2g@wiley.com', 7, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (90, 30, 'Huntlee Klimochkin', 1, '1402637620', 'hklimochkin2h@51.la', 10, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (91, 47, 'Burk Emburey', 1, '8115756785', 'bemburey2i@hud.gov', 4, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (92, 31, 'Kathryn Ionnisian', 1, '4372855972', 'kionnisian2j@icq.com', 2, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (93, 33, 'Bamby Christofor', 1, '9624076802', 'bchristofor2k@artisteer.com', 4, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (94, 38, 'Rachel Alberti', 1, '4552418809', 'ralberti2l@craigslist.org', 2, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (95, 38, 'Deck Perello', 1, '7997675214', 'dperello2m@irs.gov', 10, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (96, 40, 'Daisie Noddle', 1, '5055759899', 'dnoddle2n@hp.com', 4, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (97, 31, 'Mirilla Vaillant', 1, '3992763853', 'mvaillant2o@rediff.com', 6, 'Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (98, 42, 'Chevalier Revel', 1, '7148562041', 'crevel2p@hugedomains.com', 2, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (99, 40, 'Cherrita Poyner', 1, '9127577336', 'cpoyner2q@ycombinator.com', 3, 'Not Available');
insert into service_men (id, age, name, service_id, phone_no, email, work_experience, availability) values (100, 33, 'Jessika Depport', 1, '8261639678', 'jdepport2r@com.com', 3, 'Available');
